export const builds = {
    support: [
        {
            id: 'frb',
            value: 1,
            name: 'Support Firebrand',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/f/ff/Firebrand_tango_icon_48px.png',
        },
        {
            id: 'spl',
            value: 2,
            name: 'Shoutbreaker',
            link: 'http://en.gw2skills.net/editor/?PKwEwEmosAmEDj9xOxU6y+dB-zVJYjR3/ZkpUInVlqmmEcpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/42/Spellbreaker_tango_icon_48px.png',
        },
        {
            id: 'vnd',
            value: 3,
            name: 'Heal Vindicator',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/d/dd/Vindicator_tango_icon_48px.png',
        },
        {
            id: 'scr',
            value: 4,
            name: 'Heal Scrapper',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/4a/Scrapper_tango_icon_48px.png',
        },
        {
            id: 'drd',
            value: 5,
            name: 'Heal Druid',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/9/91/Druid_tango_icon_48px.png',
        },
        {
            id: 'tmp',
            value: 6,
            name: 'Support Tempest',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/40/Tempest_tango_icon_48px.png',
        },
        {
            id: 'chr',
            value: 7,
            name: 'Minstrel Chrono',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/f/f2/Chronomancer_tango_icon_48px.png',
        },
    ],
    damage: [
        {
            id: 'frb',
            value: 1,
            name: 'Support Firebrand',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/f/ff/Firebrand_tango_icon_48px.png',
        },
        {
            id: 'spl',
            value: 2,
            name: 'Shoutbreaker',
            link: 'http://en.gw2skills.net/editor/?PKwEwEmosAmEDj9xOxU6y+dB-zVJYjR3/ZkpUInVlqmmEcpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/42/Spellbreaker_tango_icon_48px.png',
        },
        {
            id: 'vnd',
            value: 3,
            name: 'Heal Vindicator',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/d/dd/Vindicator_tango_icon_48px.png',
        },
        {
            id: 'scr',
            value: 4,
            name: 'Heal Scrapper',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/4a/Scrapper_tango_icon_48px.png',
        },
        {
            id: 'drd',
            value: 5,
            name: 'Heal Druid',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/9/91/Druid_tango_icon_48px.png',
        },
        {
            id: 'tmp',
            value: 6,
            name: 'Support Tempest',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/40/Tempest_tango_icon_48px.png',
        },
        {
            id: 'chr',
            value: 7,
            name: 'Minstrel Chrono',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/f/f2/Chronomancer_tango_icon_48px.png',
        },
    ],
    celestial: [
        {
            id: 'frb',
            value: 1,
            name: 'Support Firebrand',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/f/ff/Firebrand_tango_icon_48px.png',
        },
        {
            id: 'spl',
            value: 2,
            name: 'Shoutbreaker',
            link: 'http://en.gw2skills.net/editor/?PKwEwEmosAmEDj9xOxU6y+dB-zVJYjR3/ZkpUInVlqmmEcpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/42/Spellbreaker_tango_icon_48px.png',
        },
        {
            id: 'vnd',
            value: 3,
            name: 'Heal Vindicator',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/d/dd/Vindicator_tango_icon_48px.png',
        },
        {
            id: 'scr',
            value: 4,
            name: 'Heal Scrapper',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/4a/Scrapper_tango_icon_48px.png',
        },
        {
            id: 'drd',
            value: 5,
            name: 'Heal Druid',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/9/91/Druid_tango_icon_48px.png',
        },
        {
            id: 'tmp',
            value: 6,
            name: 'Support Tempest',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/40/Tempest_tango_icon_48px.png',
        },
        {
            id: 'chr',
            value: 7,
            name: 'Minstrel Chrono',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/f/f2/Chronomancer_tango_icon_48px.png',
        },
    ],
    other: [
        {
            id: 'frb',
            value: 1,
            name: 'Support Firebrand',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/f/ff/Firebrand_tango_icon_48px.png',
        },
        {
            id: 'spl',
            value: 2,
            name: 'Shoutbreaker',
            link: 'http://en.gw2skills.net/editor/?PKwEwEmosAmEDj9xOxU6y+dB-zVJYjR3/ZkpUInVlqmmEcpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/42/Spellbreaker_tango_icon_48px.png',
        },
        {
            id: 'vnd',
            value: 3,
            name: 'Heal Vindicator',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/d/dd/Vindicator_tango_icon_48px.png',
        },
        {
            id: 'scr',
            value: 4,
            name: 'Heal Scrapper',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/4a/Scrapper_tango_icon_48px.png',
        },
        {
            id: 'drd',
            value: 5,
            name: 'Heal Druid',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/9/91/Druid_tango_icon_48px.png',
        },
        {
            id: 'tmp',
            value: 6,
            name: 'Support Tempest',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/4/40/Tempest_tango_icon_48px.png',
        },
        {
            id: 'chr',
            value: 7,
            name: 'Minstrel Chrono',
            link: 'http://en.gw2skills.net/editor/?PWwAYl7lRwkYYMOmJmyW7vbA-zVJYjR9/hkmCITpQ6iKNOL+fpBA-w',
            icon: 'https://wiki.guildwars2.com/images/f/f2/Chronomancer_tango_icon_48px.png',
        },
    ]
};